config/routes.rb
Rails.application.routes.draw do
  
  resources :groups
  devise_for :users
  root "pages#home"
  get "whyus" => "pages#whyus"
  get "howitworks" => "pages#howitworks"

end

app/models/group.rb
class Group < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         # Specifies a VALID password.
         validates :password, :presence => true,
                     :on => :create,
                     :format => {:with => /\A.*(?=.{10,})(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).*\Z/ }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:description)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
	end

	def whyus
	end

	def howitworks
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/application/_favicon.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= asset_path 'favicon/apple-touch-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= asset_path 'favicon/apple-touch-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= asset_path 'favicon/apple-touch-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= asset_path 'favicon/apple-touch-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= asset_path 'favicon/apple-touch-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= asset_path 'favicon/apple-touch-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= asset_path 'favicon/apple-touch-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= asset_path 'favicon/apple-touch-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= asset_path 'favicon/apple-touch-icon-180x180.png' %>">
<link rel="icon" type="image/png" href="<%= asset_path 'favicon/favicon-32x32.png' %>" sizes="32x32">
<link rel="icon" type="image/png" href="<%= asset_path 'favicon/android-chrome-192x192.png' %>" sizes="192x192">
<link rel="icon" type="image/png" href="<%= asset_path 'favicon/favicon-96x96.png' %>" sizes="96x96">
<link rel="icon" type="image/png" href="<%= asset_path 'favicon/favicon-16x16.png' %>" sizes="16x16">
<link rel="manifest" href="<%= asset_path 'favicon/manifest.json' %>">
<link rel="mask-icon" href="<%= asset_path 'favicon/safari-pinned-tab.svg' %>" color="#5bbad5">
<link rel="shortcut icon" href="<%= asset_path 'favicon/favicon.ico' %>">
<meta name="apple-mobile-web-app-title" content="StudyShark">
<meta name="application-name" content="StudyShark">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="msapplication-TileImage" content="<%= asset_path 'favicon/mstile-144x144.png' %>">
<meta name="msapplication-config" content="<%= asset_path 'favicon/browserconfig.xml' %>">
<meta name="theme-color" content="#ffffff">

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h5 class="form-control">Editing</h5>

<%= render 'form' %>

<%= link_to 'Show', @group, class: "label label-success" %> |
<%= link_to 'Back', groups_path, class: "label label-warning" %>

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<h5 class="form-control">Select or Create a Group</h5>

<div class="jumbotron center">
<table>
  <thead>
    <tr>
      <th>Groups</th>
      <th colspan="3"></th>
    </tr>
  </thead>

<div>
  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.description %></td>
        <td>|</td>
        <td><%= link_to 'Show', group, class: "label label-success" %></td>
        <td><%= link_to 'Edit', edit_group_path(group),  class: "label label-warning" %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Do you really want to delete this group?' },  class: "label label-danger"  %></td>
      </tr>
    <% end %>
  </tbody>
</div>
</table>

<br>

<%= link_to 'New Group', new_group_path, class: "btn btn-info form-control" %>
</div>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p class="panel panel-heading"> Welcome to the <strong> <%= @group.description %> </strong> Group!
</p>

<%= link_to 'Edit', edit_group_path(@group), class: "label label-warning" %> |
<%= link_to 'Back', groups_path, class: "label label-success" %>

app/views/layouts/_navBar.html.erb
</nav><nav class="navbar navbar-default">

  <div class="container-fluid">

    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">

      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">

        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
    <%= link_to "StudyShark", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav navbar-right">

        <li> <%= link_to "Why Us?", whyus_path %> </li>
        <li> <%= link_to "How It Works", howitworks_path %> </li>

        <% if user_signed_in? %>
        <li> <%= link_to "Account Settings", destroy_user_session_path, method: :delete %> </li>
        <li> <%= link_to "Sign Out", destroy_user_session_path, method: :delete %> </li>
        <% else %>
        <li> <%= link_to "Sign In", new_user_session_path %> </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_pagination.html.erb
<nav>
  <ul class="pagination">
    <li><a <%= link_to "Home", root_path %> </a></li>
    <li><a <%= link_to "Why Us?", whyus_path %> </a></li>
    <li><a <%= link_to "How It Works", howitworks_path %> </a></li>
    <% if user_signed_in? %>
        <li> <%= link_to "Sign Out", destroy_user_session_path, method: :delete %> </li>
        <% else %>
        <li> <%= link_to "Sign In", new_user_session_path %> </li>
        <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render 'favicon' %>
  <title> StudyShark | Learn With Students From Your University! | StudyShark 2016. </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

<div class="container">
<%= render "layouts/navBar" %>
</div>

<div class="container">
	<% flash.each do |name, msg| %>
		<%= content_tag(:div, msg, class: "alert alert-success") %>
		<% end %>
<%= yield %>
</div>


<div class="container">
<%= render "layouts/pagination" %>
<h6> StudyShark (Updated July 23, 2016) | William Butler | University of Maryland: College Park | Copyright 2016 </h6>
</div> 

</body>
</html>

app/views/pages/home.html.erb
<div class="jumbotron center">

	<hr>

<% if user_signed_in? %>

<p>Congratulations! You've signed in! Select the class you need help in to join the group.</p>

<%= link_to "Active Groups", groups_path, class: "btn btn-primary btn-large" %>

	<% else %>

<h2> Welcome to StudyShark! </h2>

StudyShark is a online web application that allows students to collaborate with other students from the same university.

<hr> 
	<p>
		<%= link_to "Sign In", new_user_session_path, class: "btn btn-success btn-large" %>
		<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-danger btn-large" %>
	</p>

<% end %>

</div>

app/views/pages/howitworks.html.erb
<div class="jumbotron center">

<h3> How Does StudyShark Work? </h3>

This entire website is a work in progress. Please come back later when it is complete!

</div>

app/views/pages/whyus.html.erb
<div class="jumbotron center">

<h3> Why StudyShark? </h3>

You should pick us because we're the best!

</div>